### ISSUE TITLE
Not compatible with latest tweepy-3.9.0

### ISSUE THREAD

**Issue by DaveLomber** [milesmcc/LibreNews-Server#24]
It fails with an error

```
Exception in thread Thread-1:
Traceback (most recent call last):
 File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
   self.run()
 File "/usr/lib/python2.7/threading.py", line 754, in run
   self.__target(*self.__args, **self.__kwargs)
 File "/home/ubuntu/LibreNews-Server/src/flashes.py", line 128, in streamer_entrypoint
   async=False)
TypeError: filter() got an unexpected keyword argument 'async'
```

`async` param was renamed to `is_async` in 3.7.0 https://github.com/tweepy/tweepy/commit/dc68896016e02a249a24f2204b571592cbc46de2

**Comment by milesmcc** [comment]
Got it. This definitely needs a fix. I'd gladly accept a PR, or I can get on this this weekend.

**Comment by milesmcc** [comment]
Should be fixed in the latest commit. I really should lock the dependencies; oh well — I built this a long time ago! I'm happy it still works well, though.
