### ISSUE TITLE
Getting some errors setting it up

### ISSUE THREAD

**Issue by lisbonjoker** [milesmcc/LibreNews-Server#26]
```
.local/lib/python2.7/site-packages/arrow/arrow.py:28: DeprecationWarning: Arrow will drop support for Python 2.7 and 3.5 in the upcoming v1.0.0 release. Please upgrade to Python 3.6+ to continue receiving updates for Arrow.

.local/lib/python2.7/site-packages/http_ece/__init__.py:5: Cryptography - DeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release. from cryptography.exceptions import InvalidTag
```

```
ERROR:tornado.application:Uncaught exception GET / (removed)
HTTPServerRequest(protocol='http', host='removed:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='removed')
Traceback (most recent call last):
  File ".local/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "webserver.py", line 39, in get
    say("Received INDEX request (" + req_resp + ")")
UnboundLocalError: local variable 'req_resp' referenced before assignment
ERROR:tornado.access:500 GET / (removed) 2.62ms
[LibreNews Server] [ERR] Errored while handling request IP -- still served... 
```

**Comment by milesmcc** [comment]
To be honest, I’m not sure. Verify that you’re using Python 3 — those error messages indicate to me that you’re using Python 2.

**Comment by lisbonjoker** [comment]
But the code is for Python2 no?
In Python3 I can't run it at all:
```
Traceback (most recent call last):
  File "webserver.py", line 2, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
```

**Comment by lisbonjoker** [comment]
> To start a LibreNews server, first make sure that you have Python 2 and pip installed.

Of course I would use Python 2 if I followed the instructions but to use Python 3 I had to make some changes.
https://python.readthedocs.io/en/v2.7.2/library/httplib.html

> The httplib module has been renamed to http.client in Python 3.0. The 2to3 tool will automatically adapt imports when converting your sources to 3.0.

I made a pull with someone code changes to run on Python 3 https://github.com/milesmcc/LibreNews-Server/pull/27 but one problem still remains.
